services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sensordb"]
      interval: 5s
      timeout: 5s
      retries: 5

  sensor-management-api:
    build: ./sensor-management-api
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${SENSOR_MANAGEMENT_API_PORT}:4000
    depends_on:
      - postgres
    volumes:
      - ./sensor-management-api/prisma:/app/prisma

volumes:
  postgres_data:
